trying to fix github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,13 +52,11 @@ jobs:
             echo "No test results found"
             exit 1
           fi
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: 'build/test-results/test/*.xml'   # Path to test results
-          reporter: jest-junit        # Format of test results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:        # Name of the check run which will be created
+          report_paths: 'build/test-results/test/*.xml'   # Path to test results
 #      - name: Publish Test Results
 #        uses: dorny/test-reporter@v1
 #        with:
