trying to fix github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,7 +52,13 @@ jobs:
             echo "No test results found"
             exit 1
           fi
-
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: '*.xml'   # Path to test results
+          reporter: jest-junit        # Format of test results
 #      - name: Publish Test Results
 #        uses: dorny/test-reporter@v1
 #        with:
